apiVersion: apps/v1
kind: Deployment
metadata:
  name: financial-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: financial-backend
  template:
    metadata:
      labels:
        app: financial-backend
    spec:
      containers:
        - name: backend
          image: backend:latest
          ports:
            - containerPort: 8000
