apiVersion: apps/v1
kind: Deployment
metadata:
  name: financial-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: financial-frontend
  template:
    metadata:
      labels:
        app: financial-frontend
    spec:
      containers:
        - name: frontend
          image: frontend:latest
          ports:
            - containerPort: 5173
