apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: financial-ingress
spec:
  rules:
    - host: financial.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: financial-frontend
                port:
                  number: 80
